# Generated by Django 3.2.8 on 2021-11-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_i_para', models.IntegerField(default=50)),
                ('f_t_para', models.IntegerField(default=50)),
                ('p_j_para', models.IntegerField(default=50)),
            ],
        ),
    ]
