# Generated by Django 3.2.8 on 2021-10-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_id',
            field=models.CharField(max_length=50),
        ),
    ]
