# Generated by Django 3.2.8 on 2021-11-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='n_s_para',
            field=models.IntegerField(default=50),
        ),
    ]
