# Generated by Django 3.2.8 on 2021-12-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_rename_surveyed_case_is_surveyed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_dislike',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_like',
        ),
    ]
